/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Config */
        get: operations["read_config_api_config_get"];
        /** Write Config */
        put: operations["write_config_api_config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Config
         * @description Change only the given fields, so pages editing one setting never revert another page's edits.
         */
        patch: operations["patch_config_api_config_patch"];
        trace?: never;
    };
    "/api/viz/records": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Viz Records Endpoint */
        get: operations["viz_records_endpoint_api_viz_records_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/viz/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Viz Items Endpoint */
        get: operations["viz_items_endpoint_api_viz_items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/top-merchants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Top Merchants Endpoint */
        get: operations["top_merchants_endpoint_api_analytics_top_merchants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/monthly-spend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Monthly Spend Endpoint */
        get: operations["monthly_spend_endpoint_api_analytics_monthly_spend_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/monthly-volume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Monthly Volume Endpoint */
        get: operations["monthly_volume_endpoint_api_analytics_monthly_volume_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/years": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Years Endpoint
         * @description Distinct years present in the archive, newest first.
         */
        get: operations["years_endpoint_api_years_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/date-range": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Date Range Endpoint
         * @description Earliest/latest dated document — lets the UI open on a populated period
         *     instead of an empty current month.
         */
        get: operations["date_range_endpoint_api_date_range_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/merchants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Merchants Endpoint
         * @description Every merchant/brand with totals — the selector list for the merchant page.
         *
         *     Deliberately excludes the heavy per-document fields so the UI never has to
         *     pull the full records payload just to populate a dropdown.
         */
        get: operations["merchants_endpoint_api_merchants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/merchant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Merchant Endpoint */
        get: operations["merchant_endpoint_api_analytics_merchant_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/timecapsule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Timecapsule Endpoint */
        get: operations["timecapsule_endpoint_api_analytics_timecapsule_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analytics/calendar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Calendar Endpoint */
        get: operations["calendar_endpoint_api_analytics_calendar_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/receipt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Receipt Endpoint */
        get: operations["receipt_endpoint_api_receipt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/archived/{rel_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Archived Media
         * @description Serve a file from the organized YYYY/MM (post-archive) tree.
         */
        get: operations["archived_media_api_media_archived__rel_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/media/input/{filename}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Input Media
         * @description Serve an original scan (pre-archive) by filename.
         */
        get: operations["input_media_api_media_input__filename__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Queue Endpoint
         * @description Documents awaiting review, in review order, plus progress counts.
         */
        get: operations["queue_endpoint_api_review_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Document Endpoint
         * @description Everything the review form needs for one document.
         */
        get: operations["document_endpoint_api_review_document_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/hints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hints Endpoint
         * @description Hint rules, name status and accept blocker for the form's unsaved values.
         */
        post: operations["hints_endpoint_api_review_hints_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Decide Endpoint
         * @description Record accept/mark/toss for a document. Accept is validated; mark and toss never are.
         */
        post: operations["decide_endpoint_api_review_decisions_post"];
        /**
         * Clear Endpoint
         * @description Clear every review decision (the UI confirms first).
         */
        delete: operations["clear_endpoint_api_review_decisions_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/review/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Undo Endpoint
         * @description Remove one document's decision, returning it to the queue (Undo).
         */
        delete: operations["undo_endpoint_api_review_decision_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AppConfig */
        AppConfig: {
            /**
             * Input Image Path
             * @default
             */
            input_image_path: string;
            /**
             * Batch Output Path
             * @default
             */
            batch_output_path: string;
            /**
             * Extract Structured
             * @default true
             */
            extract_structured: boolean;
            /**
             * Ocr Model
             * @default
             */
            ocr_model: string;
            /**
             * Workshop Ocr Model
             * @default
             */
            workshop_ocr_model: string;
            /**
             * Extractor Model
             * @default
             */
            extractor_model: string;
            /**
             * Workshop Extractor Model
             * @default
             */
            workshop_extractor_model: string;
            /**
             * Parse Custom Instruction
             * @default
             */
            parse_custom_instruction: string;
            /**
             * Normalize Engine
             * @default embedding
             */
            normalize_engine: string;
            /**
             * Normalize Embedding Threshold
             * @default 0.05
             */
            normalize_embedding_threshold: number;
            /**
             * Normalize String Similarity
             * @default 80
             */
            normalize_string_similarity: number;
            /**
             * Indexing Scheme
             * @default
             */
            indexing_scheme: string;
            /**
             * Dashboard Rank By
             * @default Total Spend
             */
            dashboard_rank_by: string;
            /**
             * Prefix Suggestion Boundary Only
             * @default true
             */
            prefix_suggestion_boundary_only: boolean;
            /**
             * Prefix Suggestion Max Length
             * @default 24
             */
            prefix_suggestion_max_length: number;
            /**
             * Prefix Suggestion Min Length
             * @default 3
             */
            prefix_suggestion_min_length: number;
            /**
             * Prefix Suggestion Min Count
             * @default 2
             */
            prefix_suggestion_min_count: number;
            /**
             * Calendar Period
             * @default week
             */
            calendar_period: string;
            /**
             * Calendar Date
             * @default
             */
            calendar_date: string;
        };
        /** AppConfigPatch */
        AppConfigPatch: {
            /** Input Image Path */
            input_image_path?: string | null;
            /** Batch Output Path */
            batch_output_path?: string | null;
            /** Extract Structured */
            extract_structured?: boolean | null;
            /** Ocr Model */
            ocr_model?: string | null;
            /** Workshop Ocr Model */
            workshop_ocr_model?: string | null;
            /** Extractor Model */
            extractor_model?: string | null;
            /** Workshop Extractor Model */
            workshop_extractor_model?: string | null;
            /** Parse Custom Instruction */
            parse_custom_instruction?: string | null;
            /** Normalize Engine */
            normalize_engine?: string | null;
            /** Normalize Embedding Threshold */
            normalize_embedding_threshold?: number | null;
            /** Normalize String Similarity */
            normalize_string_similarity?: number | null;
            /** Indexing Scheme */
            indexing_scheme?: string | null;
            /** Dashboard Rank By */
            dashboard_rank_by?: string | null;
            /** Prefix Suggestion Boundary Only */
            prefix_suggestion_boundary_only?: boolean | null;
            /** Prefix Suggestion Max Length */
            prefix_suggestion_max_length?: number | null;
            /** Prefix Suggestion Min Length */
            prefix_suggestion_min_length?: number | null;
            /** Prefix Suggestion Min Count */
            prefix_suggestion_min_count?: number | null;
            /** Calendar Period */
            calendar_period?: string | null;
            /** Calendar Date */
            calendar_date?: string | null;
        };
        /**
         * BoxRect
         * @description Corner-normalized rectangle on the OCR's 0-1000 scale, relative to the page image.
         */
        BoxRect: {
            /** X1 */
            x1: number;
            /** Y1 */
            y1: number;
            /** X2 */
            x2: number;
            /** Y2 */
            y2: number;
        };
        /** BrandTotals */
        BrandTotals: {
            /** Merchant Group */
            merchant_group: string;
            /** Total Spend */
            total_spend: number;
            /** Visit Count */
            visit_count: number;
            /** Brand Id */
            brand_id: string | null;
            /** Avg Per Visit */
            avg_per_visit: number;
        };
        /** CadencePoint */
        CadencePoint: {
            /** Visit Date */
            visit_date: string;
            /** Days Since Last */
            days_since_last: number;
        };
        /** DateRange */
        DateRange: {
            /** Min */
            min: string | null;
            /** Max */
            max: string | null;
        };
        /** DecisionIn */
        DecisionIn: {
            /** Key */
            key: string;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "accepted" | "marked" | "tossed";
            draft: components["schemas"]["DraftIn"];
            /**
             * Comment
             * @default
             */
            comment: string;
        };
        /** DecisionOut */
        DecisionOut: {
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "accepted" | "marked" | "tossed";
            /** Document Type */
            document_type: string;
            /** Name */
            name: string;
            /** Date */
            date: string;
            /** Time */
            time: string;
            /** Cost */
            cost: number;
            /** Currency */
            currency: string;
            /** Comment */
            comment: string;
        };
        /** DraftIn */
        DraftIn: {
            /**
             * Document Type
             * @enum {string}
             */
            document_type: "receipt" | "other" | "corrupted";
            /** Name */
            name: string;
            /** Date */
            date: string;
            /** Time */
            time: string;
            /** Cost */
            cost: number | null;
            /** Currency */
            currency: string;
        };
        /** FieldBoxOut */
        FieldBoxOut: {
            /** Index */
            index: number;
            /** Fields */
            fields: string[];
            /** Rects */
            rects: components["schemas"]["BoxRect"][];
            /** Text */
            text: string | null;
        };
        /** FormDefaultsOut */
        FormDefaultsOut: {
            /**
             * Document Type
             * @enum {string}
             */
            document_type: "receipt" | "other" | "corrupted";
            /** Name */
            name: string;
            /** Date */
            date: string;
            /** Time */
            time: string;
            /** Cost */
            cost: number;
            /** Currency */
            currency: string;
            /** Phone */
            phone: string;
        };
        /**
         * GalleryReceipt
         * @description Slim receipt for galleries: no OCR text or line items.
         */
        GalleryReceipt: {
            /** Filename */
            filename: string;
            /** Path */
            path: string;
            /** Date */
            date: string;
            /** Time */
            time: string;
            /** Cost */
            cost: number;
            /** Currency */
            currency: string;
            /** Name */
            name: string;
            /** Brand Location */
            brand_location: string;
            /** Document Type */
            document_type: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Status */
            status: string;
        };
        /** HintOut */
        HintOut: {
            /** Message */
            message: string;
            /** Color */
            color: string;
        };
        /** HintsRequest */
        HintsRequest: {
            /** Key */
            key: string;
            draft: components["schemas"]["DraftIn"];
        };
        /**
         * HintsResponse
         * @description ``accept_error`` is why Accept would be refused for these values (None if it wouldn't be).
         */
        HintsResponse: {
            /** Hints */
            hints: components["schemas"]["HintOut"][];
            /**
             * Name Status
             * @enum {string}
             */
            name_status: "placeholder" | "approved" | "unseen";
            /** Accept Error */
            accept_error: string | null;
        };
        /** ItemBreakdownRow */
        ItemBreakdownRow: {
            /** Item Name */
            item_name: string;
            /** Times Purchased */
            times_purchased: number;
            /** Total Spent */
            total_spent: number;
            /** Avg Unit Price */
            avg_unit_price: number | null;
        };
        /** LineItem */
        LineItem: {
            /** Name */
            name: string;
            /** Quantity */
            quantity: number | null;
            /** Unit Price */
            unit_price: number | null;
            /** Total Price */
            total_price: number | null;
        };
        /** MerchantMetrics */
        MerchantMetrics: {
            /** Total Spend */
            total_spend: number;
            /** Visit Count */
            visit_count: number;
            /** Avg Ticket */
            avg_ticket: number;
            /** Currency */
            currency: string;
            /** First Visit */
            first_visit: string | null;
            /** Last Visit */
            last_visit: string | null;
            /** Avg Gap */
            avg_gap: number | null;
        };
        /** MerchantProfile */
        MerchantProfile: {
            metrics: components["schemas"]["MerchantMetrics"];
            /** Trend */
            trend: components["schemas"]["MonthlySpend"][];
            /** Cadence */
            cadence: components["schemas"]["CadencePoint"][];
            /** Items */
            items: components["schemas"]["ItemBreakdownRow"][];
            /** Receipts */
            receipts: components["schemas"]["GalleryReceipt"][];
        };
        /** MonthlySpend */
        MonthlySpend: {
            /** Period */
            period: string;
            /** Spend */
            spend: number;
            /** Month Ts */
            month_ts: string;
        };
        /** MonthlyVolume */
        MonthlyVolume: {
            /** Period */
            period: string;
            /** Count */
            count: number;
            /** Month Ts */
            month_ts: string;
        };
        /** NameTotals */
        NameTotals: {
            /** Name */
            name: string;
            /** Total Spend */
            total_spend: number;
            /** Visit Count */
            visit_count: number;
            /** Brand Id */
            brand_id: string | null;
            /** Avg Per Visit */
            avg_per_visit: number;
        };
        /** QueueItem */
        QueueItem: {
            /** Key */
            key: string;
            /**
             * Document Type
             * @enum {string}
             */
            document_type: "receipt" | "other" | "corrupted";
            /** Label */
            label: string;
        };
        /** ReviewDocument */
        ReviewDocument: {
            /** Key */
            key: string;
            defaults: components["schemas"]["FormDefaultsOut"];
            /** Initial Name */
            initial_name: string;
            /** Ocr Text */
            ocr_text: string;
            /** Pages */
            pages: components["schemas"]["ReviewPage"][];
            /** Smart Matches */
            smart_matches: components["schemas"]["SmartMatch"][];
            decision: components["schemas"]["DecisionOut"] | null;
        };
        /** ReviewPage */
        ReviewPage: {
            /** File Key */
            file_key: string;
            /** Filename */
            filename: string | null;
            /** Image Available */
            image_available: boolean;
            /** Boxes */
            boxes: components["schemas"]["FieldBoxOut"][];
        };
        /**
         * ReviewQueue
         * @description ``blocker`` explains why there is nothing to review yet (no index, no extractions).
         */
        ReviewQueue: {
            /** Blocker */
            blocker: string | null;
            summary: components["schemas"]["ReviewSummary"];
            /** Items */
            items: components["schemas"]["QueueItem"][];
        };
        /** ReviewSummary */
        ReviewSummary: {
            /** Total */
            total: number;
            /** Pending */
            pending: number;
            /** Verdicts */
            verdicts: components["schemas"]["VerdictCount"][];
        };
        /** SmartMatch */
        SmartMatch: {
            /** Name */
            name: string;
            /** Name Score */
            name_score: number;
            /** Phone Score */
            phone_score: number;
            /** Quick Apply */
            quick_apply: boolean;
            /** Label */
            label: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VerdictCount */
        VerdictCount: {
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "accepted" | "marked" | "tossed";
            /** Label */
            label: string;
            /** Color */
            color: string;
            /** Count */
            count: number;
        };
        /**
         * VizItem
         * @description One line item across all archived receipts.
         */
        VizItem: {
            /** Filename */
            filename: string;
            /** Merchant */
            merchant: string;
            /** Merchant Group */
            merchant_group: string;
            /** Receipt Date */
            receipt_date: string;
            /** Parsed Date */
            parsed_date: string | null;
            /** Item Name */
            item_name: string;
            /** Quantity */
            quantity: number | null;
            /** Unit Price */
            unit_price: number | null;
            /** Total Price */
            total_price: number | null;
            /** Currency */
            currency: string;
        };
        /**
         * VizRecord
         * @description One archived document (multi-page documents collapsed to their first page).
         */
        VizRecord: {
            /** Filename */
            filename: string;
            /** Path */
            path: string;
            /** Paths */
            paths: string[];
            /** Document Type */
            document_type: string;
            /** Name */
            name: string;
            /** Date */
            date: string;
            /** Time */
            time: string;
            /** Cost */
            cost: number;
            /** Currency */
            currency: string;
            /** Comment */
            comment: string;
            /** Address */
            address: string;
            /** Language */
            language: string;
            /** Items */
            items: components["schemas"]["LineItem"][];
            /** Ocr Markdown */
            ocr_markdown: string;
            /** Parsed Date */
            parsed_date: string | null;
            /** Year */
            year: number | null;
            /** Month */
            month: number | null;
            /** Brand Id */
            brand_id: string | null;
            /** Brand Label */
            brand_label: string | null;
            /** Brand Location */
            brand_location: string;
            /** Merchant Group */
            merchant_group: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppConfig"];
                };
            };
        };
    };
    write_config_api_config_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_config_api_config_patch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AppConfigPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    viz_records_endpoint_api_viz_records_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VizRecord"][];
                };
            };
        };
    };
    viz_items_endpoint_api_viz_items_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VizItem"][];
                };
            };
        };
    };
    top_merchants_endpoint_api_analytics_top_merchants_get: {
        parameters: {
            query?: {
                group_by?: "brand" | "name";
                rank_by?: "total_spend" | "visit_count";
                top_n?: number;
                year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandTotals"][] | components["schemas"]["NameTotals"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    monthly_spend_endpoint_api_analytics_monthly_spend_get: {
        parameters: {
            query?: {
                year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlySpend"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    monthly_volume_endpoint_api_analytics_monthly_volume_get: {
        parameters: {
            query?: {
                year?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MonthlyVolume"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    years_endpoint_api_years_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number[];
                };
            };
        };
    };
    date_range_endpoint_api_date_range_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DateRange"];
                };
            };
        };
    };
    merchants_endpoint_api_merchants_get: {
        parameters: {
            query?: {
                group_by?: "brand" | "name";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BrandTotals"][] | components["schemas"]["NameTotals"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    merchant_endpoint_api_analytics_merchant_get: {
        parameters: {
            query?: {
                name?: string | null;
                brand_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MerchantProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    timecapsule_endpoint_api_analytics_timecapsule_get: {
        parameters: {
            query: {
                month: number;
                day: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VizRecord"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    calendar_endpoint_api_analytics_calendar_get: {
        parameters: {
            query: {
                start: string;
                end: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["VizRecord"][];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    receipt_endpoint_api_receipt_get: {
        parameters: {
            query: {
                file: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VizRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archived_media_api_media_archived__rel_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rel_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    input_media_api_media_input__filename__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                filename: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    queue_endpoint_api_review_queue_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewQueue"];
                };
            };
        };
    };
    document_endpoint_api_review_document_get: {
        parameters: {
            query: {
                key: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hints_endpoint_api_review_hints_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HintsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HintsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_endpoint_api_review_decisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_endpoint_api_review_decisions_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSummary"];
                };
            };
        };
    };
    undo_endpoint_api_review_decision_delete: {
        parameters: {
            query: {
                key: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
